version: 2.1

orbs:
  haskell: haskell-works/haskell-build@4.1.8
  aws-s3: circleci/aws-s3@1.0.16

jobs:
  publish-s3:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - attach_workspace:
          at: /tmp/attachment

      - run:
          name: Prepare uploads
          command: |
            mkdir -p /tmp/publish

            for x in $(find /tmp/attachment -name project.env); do
              src_path="$(dirname $x)"
              arch="$(basename $src_path)"
              echo $src_path $arch
              (  . "$src_path/project.env"
                tar -zcvf "/tmp/publish/$BUILD_EXE_NAME-$BUILD_EXE_VERSION-$arch.tar.gz" -C "$src_path/dist" .
              )
            done
      - aws-s3/sync:
          aws-access-key-id: DL_RW_AWS_ACCESS_KEY_ID
          aws-region: DL_RW_AWS_REGION
          aws-secret-access-key: DL_RW_AWS_SECRET_ACCESS_KEY
          from: /tmp/publish
          overwrite: true
          to: 's3://dl.haskellworks.io/binaries/hlint'

workflows:
  multiple-ghc-build:
    jobs:
      - haskell/build-with-binary-cache:
          name: GHC 8.6.5
          executor: haskell/ghc-8_6_5
          context: haskell-ci
          after-checkout:
            - run:
                name: Download source
                command: |
                  cabal update
                  cabal get hlint-3.1.6
                  echo "packages: $(ls */*.cabal | cut -d / -f 1)" > cabal.project
          binary-cache-uri: ${BINARY_CACHE_URI-"http://hw-binary-cache-us-west-2-a.s3-website-us-west-2.amazonaws.com/archive"}
          cabal-build-extra: --write-ghc-environment-files=ghc8.4.4+
          cabal-test-extra: --test-show-details=direct --test-options='+RTS -g1'
          fail-incoherent-builds: false
          workspace-dir: workspace/x86_64-linux
          write-result-workspace: true

      - publish-s3:
          requires: [GHC 8.6.5]
